/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import sam.Historico;
import sam.RegistroDeAplicacao;

/**
 *
 * @author dioni
 */
public class TelaHistorico extends javax.swing.JFrame {
    
    Historico historico = new Historico();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form TelaHistorico
     */
    public TelaHistorico() {
        initComponents();
        carregarTabelaHistorico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        pnlPesquisaHistorico = new javax.swing.JPanel();
        btnPesquisar = new javax.swing.JButton();
        lblNomeDoPaciente = new javax.swing.JLabel();
        lbnCpfDoPaciente = new javax.swing.JLabel();
        lbnNomeEnfermeiro = new javax.swing.JLabel();
        lblCoren = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblMedicamento = new javax.swing.JLabel();
        txtNomeDoPaciente = new javax.swing.JTextField();
        txtCpfDoPaciente = new javax.swing.JTextField();
        txtNomeEnfermeiro = new javax.swing.JTextField();
        txtCoren = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        cboxMedicamento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHistorico = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SAM - Histórico");
        setPreferredSize(new java.awt.Dimension(820, 580));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 16, 127));
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("SAM - Sistema de Administração de Medicamentos");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        pnlPesquisaHistorico.setBackground(new java.awt.Color(204, 204, 255));
        pnlPesquisaHistorico.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Busca Personalizada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/historico 32px.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblNomeDoPaciente.setText("Nome do paciente:");

        lbnCpfDoPaciente.setText("CPF do paciente:");

        lbnNomeEnfermeiro.setText("Nome do(a) enfermeiro(a):");

        lblCoren.setText("COREN:");

        lblData.setText("Data (DD/MM/AAAA):");

        lblMedicamento.setText("Medicamento:");

        txtNomeDoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDoPacienteActionPerformed(evt);
            }
        });

        cboxMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vazio", "Benzetacil", "Dipirona", "Heparina", "Insulina", "Paracetamol", "Penicilina" }));
        cboxMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxMedicamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPesquisaHistoricoLayout = new javax.swing.GroupLayout(pnlPesquisaHistorico);
        pnlPesquisaHistorico.setLayout(pnlPesquisaHistoricoLayout);
        pnlPesquisaHistoricoLayout.setHorizontalGroup(
            pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisaHistoricoLayout.createSequentialGroup()
                .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPesquisaHistoricoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMedicamento)
                            .addComponent(lblCoren)
                            .addComponent(lblData)))
                    .addGroup(pnlPesquisaHistoricoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbnNomeEnfermeiro))
                    .addComponent(lbnCpfDoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeDoPaciente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPesquisaHistoricoLayout.createSequentialGroup()
                        .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNomeDoPaciente)
                                .addComponent(txtCpfDoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNomeEnfermeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                            .addComponent(txtCoren, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPesquisaHistoricoLayout.createSequentialGroup()
                        .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        pnlPesquisaHistoricoLayout.setVerticalGroup(
            pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesquisaHistoricoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeDoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeDoPaciente))
                .addGap(4, 4, 4)
                .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfDoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnCpfDoPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnNomeEnfermeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoren))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPesquisaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicamento)
                    .addComponent(cboxMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesquisaHistoricoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisar)
                .addContainerGap())
        );

        tbHistorico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, "", null, "", null, "", ""},
                {"", null, "", null, "", null, "", ""},
                {"", null, "", null, "", null, "", ""},
                {"", null, "", null, "", null, "", ""},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Enfermeiro", "COREN", "Paciente", "CPF Paciente", "Medicamento", "Dosagem Aplicada", "Unidade de Medida", "Data/Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbHistorico);

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar2.png"))); // NOI18N
        btnAtualizar.setText("Limpar Filtros");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPesquisaHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPesquisaHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        
        String nomeEnfermeiro = (txtNomeEnfermeiro.getText().trim().isEmpty()) ? null : txtNomeEnfermeiro.getText();
        String coren = (txtCoren.getText().trim().isEmpty()) ? null : txtCoren.getText();
        String nomePaciente = (txtNomeDoPaciente.getText().trim().isEmpty()) ? null : txtNomeDoPaciente.getText();
        String cpfPaciente = (txtCpfDoPaciente.getText().trim().isEmpty()) ? null : txtCpfDoPaciente.getText();
        String nomeMedicamento = (((String) cboxMedicamento.getSelectedItem()).trim().equals("vazio")) ? null : ((String) cboxMedicamento.getSelectedItem()).trim();
        LocalDate data = (txtData.getText().trim().isEmpty()) ? null : LocalDate.parse(txtData.getText(), formatter);
        
        carregarPesquisa(historico.filtrarRegistro(nomeEnfermeiro, coren, nomePaciente, cpfPaciente, nomeMedicamento, data));
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        carregarTabelaHistorico();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtNomeDoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDoPacienteActionPerformed

    private void cboxMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxMedicamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistorico().setVisible(true);
            }
        });
    }
    
    public void carregarTabelaHistorico() {
        historico.carregarHistorico();
        ArrayList<RegistroDeAplicacao> listaHistorico = historico.getHistorico();
        
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Enfermeiro", "Coren", "Paciente", "CPF Paciente", "Medicamento", "Dosagem Aplicada", "Unidade de Medida", "Data/Hora"}, 0);
        for(int i=0; i<listaHistorico.size(); i++) {
            Object linha[] = new Object[]{listaHistorico.get(i).getNomeEnfermeiro(),
                                        listaHistorico.get(i).getCoren(),
                                        listaHistorico.get(i).getNomePaciente(),
                                        listaHistorico.get(i).getCpfPaciente(),
                                        listaHistorico.get(i).getNomeMedicamento(),
                                        listaHistorico.get(i).getDosagemAplicada(),
                                        listaHistorico.get(i).getUnidadeDeMedida(),
                                        listaHistorico.get(i).getData()};
            model.addRow(linha);
        }
        
        tbHistorico.setModel(model);
    }
    
    public void carregarPesquisa(ArrayList<RegistroDeAplicacao> resultadoBusca) {
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Enfermeiro", "Coren", "Paciente", "CPF Paciente", "Medicamento", "Dosagem Aplicada", "Unidade de Medida", "Data/Hora"}, 0);
        for(int i=0; i<resultadoBusca.size(); i++) {
            Object linha[] = new Object[]{resultadoBusca.get(i).getNomeEnfermeiro(),
                                        resultadoBusca.get(i).getCoren(),
                                        resultadoBusca.get(i).getNomePaciente(),
                                        resultadoBusca.get(i).getCpfPaciente(),
                                        resultadoBusca.get(i).getNomeMedicamento(),
                                        resultadoBusca.get(i).getDosagemAplicada(),
                                        resultadoBusca.get(i).getUnidadeDeMedida(),
                                        resultadoBusca.get(i).getData()};
            model.addRow(linha);
        }
        
        tbHistorico.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cboxMedicamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCoren;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblNomeDoPaciente;
    private javax.swing.JLabel lbnCpfDoPaciente;
    private javax.swing.JLabel lbnNomeEnfermeiro;
    private javax.swing.JPanel pnlPesquisaHistorico;
    private javax.swing.JTable tbHistorico;
    private javax.swing.JTextField txtCoren;
    private javax.swing.JTextField txtCpfDoPaciente;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtNomeDoPaciente;
    private javax.swing.JTextField txtNomeEnfermeiro;
    // End of variables declaration//GEN-END:variables
}
