package Telas;

public class TelaCadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPaciente
     */
    public TelaCadastroPaciente() {
        initComponents();
        
        // Habilitar e desabilitar botões
        btnNovoPaciente.setEnabled(true);
        btnBuscarPaciente.setEnabled(true);
        btnSairPaciente.setEnabled(true);
        btnSalvarPaciente.setEnabled(false);
        btnExcluirPaciente.setEnabled(false);
        btnCancelarAcaoPaciente.setEnabled(false);
        btnEditarPaciente.setEnabled(false);
        btnLimparCamposPaciente.setEnabled(false);
     
        
        // Habilitar e desabilitar campos de texto
        txtAlturaPaciente.setEnabled(false);
        txtNomePaciente.setEnabled(false);
        txtCpfPaciente.setEnabled(false);
        txtIdadePaciente.setEnabled(false);
        txtPesoPaciente.setEnabled(false);
        txtfDataNascimento.setEnabled(false);
        cbAlergias.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadosPaciente = new javax.swing.JPanel();
        lblNomePaciente = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JTextField();
        lblCpfPaciente = new javax.swing.JLabel();
        txtCpfPaciente = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        txtfDataNascimento = new javax.swing.JFormattedTextField();
        lblIdadePaciente = new javax.swing.JLabel();
        txtIdadePaciente = new javax.swing.JTextField();
        lblPesoPaciente = new javax.swing.JLabel();
        txtAlturaPaciente = new javax.swing.JTextField();
        lblAlturaPaciente = new javax.swing.JLabel();
        txtPesoPaciente = new javax.swing.JTextField();
        cbAlergias = new javax.swing.JComboBox<>();
        lblAlergiasPaciente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNovoPaciente = new javax.swing.JButton();
        btnSalvarPaciente = new javax.swing.JButton();
        btnExcluirPaciente = new javax.swing.JButton();
        btnCancelarAcaoPaciente = new javax.swing.JButton();
        btnEditarPaciente = new javax.swing.JButton();
        btnBuscarPaciente = new javax.swing.JButton();
        btnNovaPrescricao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSairPaciente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnLimparCamposPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pacientes");

        pnlDadosPaciente.setBackground(new java.awt.Color(153, 153, 255));
        pnlDadosPaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNomePaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomePaciente.setForeground(new java.awt.Color(51, 51, 51));
        lblNomePaciente.setText("Nome");

        txtNomePaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtNomePaciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNomePaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtNomePaciente.setToolTipText("Insira o nome do paciente");

        lblCpfPaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCpfPaciente.setForeground(new java.awt.Color(51, 51, 51));
        lblCpfPaciente.setText("CPF");

        txtCpfPaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtCpfPaciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCpfPaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtCpfPaciente.setToolTipText("Insira o cpf do paciente");
        txtCpfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfPacienteActionPerformed(evt);
            }
        });

        lblDataNascimento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDataNascimento.setForeground(new java.awt.Color(51, 51, 51));
        lblDataNascimento.setText("Data de Nascimento");

        txtfDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        txtfDataNascimento.setForeground(new java.awt.Color(0, 0, 0));
        txtfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtfDataNascimento.setToolTipText("Insira a data de nascimento do paciente");
        txtfDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDataNascimentoActionPerformed(evt);
            }
        });

        lblIdadePaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIdadePaciente.setForeground(new java.awt.Color(51, 51, 51));
        lblIdadePaciente.setText("Idade");

        txtIdadePaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtIdadePaciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIdadePaciente.setForeground(new java.awt.Color(51, 51, 51));
        txtIdadePaciente.setToolTipText("Insira a idade do paciente");

        lblPesoPaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPesoPaciente.setForeground(new java.awt.Color(51, 51, 51));
        lblPesoPaciente.setText("Peso (Kg)");

        txtAlturaPaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtAlturaPaciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAlturaPaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtAlturaPaciente.setToolTipText("Insira a altura do paciente em cm");
        txtAlturaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaPacienteActionPerformed(evt);
            }
        });

        lblAlturaPaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAlturaPaciente.setForeground(new java.awt.Color(51, 51, 51));
        lblAlturaPaciente.setText("Altura (cm)");

        txtPesoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtPesoPaciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPesoPaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtPesoPaciente.setToolTipText("Insira o peso do paciente em Kg");
        txtPesoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoPacienteActionPerformed(evt);
            }
        });

        cbAlergias.setBackground(new java.awt.Color(255, 255, 255));
        cbAlergias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbAlergias.setForeground(new java.awt.Color(51, 51, 51));
        cbAlergias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Nenhuma", "Penicilina", "Benzetacil", "Dipirona", "Paracetamol", "Insulina", "Heparina", "Outro" }));
        cbAlergias.setToolTipText("Selecione os medicamentos que o paciente tem alergia");
        cbAlergias.setBorder(null);
        cbAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlergiasActionPerformed(evt);
            }
        });

        lblAlergiasPaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAlergiasPaciente.setForeground(new java.awt.Color(51, 51, 51));
        lblAlergiasPaciente.setText("Alergias");
        lblAlergiasPaciente.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnNovoPaciente.setBackground(new java.awt.Color(204, 204, 204));
        btnNovoPaciente.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnNovoPaciente.setForeground(new java.awt.Color(51, 51, 51));
        btnNovoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionarpaciente 32px.png"))); // NOI18N
        btnNovoPaciente.setText("Novo");
        btnNovoPaciente.setToolTipText("Cadastrar novo paciente");
        btnNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPacienteActionPerformed(evt);
            }
        });

        btnSalvarPaciente.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarPaciente.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSalvarPaciente.setForeground(new java.awt.Color(51, 51, 51));
        btnSalvarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvarPaciente 32px.png"))); // NOI18N
        btnSalvarPaciente.setText("Salvar");
        btnSalvarPaciente.setToolTipText("Salvar paciente");

        btnExcluirPaciente.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluirPaciente.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnExcluirPaciente.setForeground(new java.awt.Color(51, 51, 51));
        btnExcluirPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluirPaciente 32px.png"))); // NOI18N
        btnExcluirPaciente.setText("Excluir");
        btnExcluirPaciente.setToolTipText("Excluir paciente cadastrado");

        btnCancelarAcaoPaciente.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarAcaoPaciente.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnCancelarAcaoPaciente.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarAcaoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar 32px.png"))); // NOI18N
        btnCancelarAcaoPaciente.setText("Cancelar");
        btnCancelarAcaoPaciente.setToolTipText("Cancelar ação");
        btnCancelarAcaoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAcaoPacienteActionPerformed(evt);
            }
        });

        btnEditarPaciente.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarPaciente.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnEditarPaciente.setForeground(new java.awt.Color(51, 51, 51));
        btnEditarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editarPaciente 32px.png"))); // NOI18N
        btnEditarPaciente.setText("Editar");
        btnEditarPaciente.setToolTipText("Editar dados do paciente");

        btnBuscarPaciente.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarPaciente.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnBuscarPaciente.setForeground(new java.awt.Color(51, 51, 51));
        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscaPaciente 32px.png"))); // NOI18N
        btnBuscarPaciente.setText("Buscar");
        btnBuscarPaciente.setToolTipText("Buscar paciente por nome ou cpf");
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        btnNovaPrescricao.setBackground(new java.awt.Color(204, 204, 204));
        btnNovaPrescricao.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnNovaPrescricao.setForeground(new java.awt.Color(51, 51, 51));
        btnNovaPrescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/prescricao 32px.png"))); // NOI18N
        btnNovaPrescricao.setText("Prescrição");
        btnNovaPrescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPrescricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnNovoPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarAcaoPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovaPrescricao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoPaciente)
                    .addComponent(btnSalvarPaciente)
                    .addComponent(btnExcluirPaciente)
                    .addComponent(btnCancelarAcaoPaciente)
                    .addComponent(btnEditarPaciente)
                    .addComponent(btnBuscarPaciente)
                    .addComponent(btnNovaPrescricao))
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(0, 16, 127));

        btnSairPaciente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSairPaciente.setForeground(new java.awt.Color(0, 0, 0));
        btnSairPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair 32px.png"))); // NOI18N
        btnSairPaciente.setText("SAIR");
        btnSairPaciente.setContentAreaFilled(false);
        btnSairPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSairPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSairPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE)
        );

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Prescrição", "Peso", "Altura", "Idade", "Data de Nascimento", "Alergias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnLimparCamposPaciente.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparCamposPaciente.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnLimparCamposPaciente.setForeground(new java.awt.Color(51, 51, 51));
        btnLimparCamposPaciente.setText("Limpar");
        btnLimparCamposPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosPacienteLayout = new javax.swing.GroupLayout(pnlDadosPaciente);
        pnlDadosPaciente.setLayout(pnlDadosPacienteLayout);
        pnlDadosPacienteLayout.setHorizontalGroup(
            pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                        .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCpfPaciente)
                            .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                                .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                                        .addComponent(lblNomePaciente)
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                                                .addGap(339, 339, 339)
                                                .addComponent(btnLimparCamposPaciente))))
                                    .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                                        .addComponent(lblDataNascimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111)
                                .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                                        .addComponent(lblIdadePaciente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIdadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                                            .addComponent(lblPesoPaciente)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPesoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosPacienteLayout.createSequentialGroup()
                                            .addComponent(lblAlturaPaciente)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtAlturaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                                .addComponent(lblAlergiasPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(205, Short.MAX_VALUE))))
        );
        pnlDadosPacienteLayout.setVerticalGroup(
            pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPacienteLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePaciente)
                    .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfPaciente)
                    .addComponent(txtAlturaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlturaPaciente))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIdadePaciente)
                        .addComponent(txtIdadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDataNascimento)
                        .addComponent(txtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(pnlDadosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlergiasPaciente)
                    .addComponent(btnLimparCamposPaciente))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDadosPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDadosPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfPacienteActionPerformed

    private void txtfDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDataNascimentoActionPerformed

    private void txtAlturaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaPacienteActionPerformed

    private void txtPesoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoPacienteActionPerformed

    private void cbAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlergiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAlergiasActionPerformed

    private void btnNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPacienteActionPerformed
        // Habilitar ou desabilitar botões
        btnNovoPaciente.setEnabled(false);
        btnSalvarPaciente.setEnabled(true);
        btnCancelarAcaoPaciente.setEnabled(true);
        btnEditarPaciente.setEnabled(false);
        btnExcluirPaciente.setEnabled(false);
        btnBuscarPaciente.setEnabled(false);
        btnNovaPrescricao.setEnabled(false);
        txtNomePaciente.requestFocus();
        btnLimparCamposPaciente.setEnabled(true);
  
        // Habilitar ou desabilitar campos de texto
        txtAlturaPaciente.setEnabled(true);
        txtCpfPaciente.setEnabled(true);
        txtNomePaciente.setEnabled(true);
        txtIdadePaciente.setEnabled(true);
        txtPesoPaciente.setEnabled(true);
        txtfDataNascimento.setEnabled(true);
        txtfDataNascimento.setEnabled(true);
        cbAlergias.setEnabled(true);
    }//GEN-LAST:event_btnNovoPacienteActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
       
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void btnSairPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPacienteActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairPacienteActionPerformed

    private void btnCancelarAcaoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAcaoPacienteActionPerformed
        txtAlturaPaciente.setText("");
        txtCpfPaciente.setText("");
        txtNomePaciente.setText("");
        txtIdadePaciente.setText("");
        txtPesoPaciente.setText("");
        txtfDataNascimento.setText("");
        
        btnBuscarPaciente.setEnabled(false);
        btnEditarPaciente.setEnabled(false);
        btnExcluirPaciente.setEnabled(false);
        btnNovaPrescricao.setEnabled(false);
        btnSairPaciente.setEnabled(true);
        btnSalvarPaciente.setEnabled(false);
        btnNovoPaciente.setEnabled(true);
        btnNovaPrescricao.setEnabled(true);
        btnBuscarPaciente.setEnabled(true);
        btnLimparCamposPaciente.setEnabled(false);
        
        txtAlturaPaciente.setEnabled(false);
        txtCpfPaciente.setEnabled(false);
        txtIdadePaciente.setEnabled(false);
        txtNomePaciente.setEnabled(false);
        txtPesoPaciente.setEnabled(false);
        txtfDataNascimento.setEnabled(false);
        cbAlergias.setEnabled(false);
       
        
        
    }//GEN-LAST:event_btnCancelarAcaoPacienteActionPerformed

    private void btnNovaPrescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPrescricaoActionPerformed
        new TelaCadastroPrescricao().setVisible(true);
    }//GEN-LAST:event_btnNovaPrescricaoActionPerformed

    private void btnLimparCamposPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposPacienteActionPerformed
        txtAlturaPaciente.setText("");
        txtPesoPaciente.setText("");
        txtIdadePaciente.setText("");
        txtNomePaciente.setText("");
        txtfDataNascimento.setText("");
        txtCpfPaciente.setText("");
        cbAlergias.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparCamposPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnCancelarAcaoPaciente;
    private javax.swing.JButton btnEditarPaciente;
    private javax.swing.JButton btnExcluirPaciente;
    private javax.swing.JButton btnLimparCamposPaciente;
    private javax.swing.JButton btnNovaPrescricao;
    private javax.swing.JButton btnNovoPaciente;
    private javax.swing.JButton btnSairPaciente;
    private javax.swing.JButton btnSalvarPaciente;
    private javax.swing.JComboBox<String> cbAlergias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAlergiasPaciente;
    private javax.swing.JLabel lblAlturaPaciente;
    private javax.swing.JLabel lblCpfPaciente;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblIdadePaciente;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblPesoPaciente;
    private javax.swing.JPanel pnlDadosPaciente;
    private javax.swing.JTextField txtAlturaPaciente;
    private javax.swing.JTextField txtCpfPaciente;
    private javax.swing.JTextField txtIdadePaciente;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtPesoPaciente;
    private javax.swing.JFormattedTextField txtfDataNascimento;
    // End of variables declaration//GEN-END:variables
}
